### ISSUE TITLE
Domain expired?

### ISSUE THREAD

**Issue by paulcpederson** [ungoldman/meowl.party#5]
meowl.party seems to be down, if you need somebody to transfer the domain to I'd be willing to buy it.

**Comment by ungoldman** [comment]
Yeah I let it die.

![](https://media.giphy.com/media/96quMvXlWpwRO/giphy.gif)

**Comment by ungoldman** [comment]
Looks like namecheap is still holding it for me in a "grace" period.

They wanted 30 bucks so I said nah. But now it's 9.98.

**Comment by paulcpederson** [comment]
I will buy/host if you don't feel like shelling out $10.

**Comment by paulcpederson** [comment]
also, meowl.club is only .99¢

**Comment by ungoldman** [comment]
I paid for years of meowls but didn't put much into the site, it's all yours when it lapses.
I bequeath it unto you.
Happy to let the meowls step up in the club as well.

**Comment by ungoldman** [comment]
also the 99¢ price tag is what inspired me to buy meowl.party in the first place, it jumps to ~30 a year (for party at least) after that. if you can buy five years at 99 cents a year that's the real power move

**Comment by jgravois** [comment]
> if you can buy five years at 99 cents a year that's the real power move

if that's _not_ an option and we decide to perpetually alternate 99 cent vanity domains, i'll sign up for 2019.

**Comment by paulcpederson** [comment]
_1 dollar shop hop_

**Comment by ungoldman** [comment]
thank you both for rallying to save the meowls

**Comment by ungoldman** [comment]
@paulcpederson do you still hear the meowl's cry? if not i'm going to transfer this repo to my user account and archive it. you have 3 days.

**Comment by jgravois** [comment]
@paulcpederson ask him to wait until the next full moon at least. 🌚

![owl babies](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSR4lVdDnCUKfnl_Ul0y0WmPb0W5fQEaHcpEA&usqp=CAU)

**Comment by paulcpederson** [comment]
I think we can sunset the meowls. 🌆 🦉 🐱

**Comment by ungoldman** [comment]
https://ungoldman.github.io/meowl.party/
